name: nxinx page CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run nginx container with site
      run: |
        docker run \
        -v ${{ github.workspace }}:/usr/share/nginx/html -p 80:80 -d nginx
